const data = [
  {
    title: 'Adnams Ghost Ship Bottle Beer 0.5%',
    brand: 'Adnams',
    abv: '0.5',
    calories: '23',
    type: 'Beer',
    ingredients: 'Water, Malted Barley, Malted Rye, Hops, Yeast',
    country: 'UK',
    volume: '500',
  },
  {
    title: 'Bavaria 0.0% Beer',
    brand: 'Bavaria',
    abv: '0',
    calories: '24',
    type: 'Beer',
    ingredients:
      'Natural Mineral Water, Barley Malt, Glucose Syrup, Hop Extract, Flavouring',
    country: 'Netherlands',
    volume: '330',
  },
  {
    title: 'Becks Blue Alcohol Free',
    brand: 'Becks',
    abv: '0.05',
    calories: '14',
    type: 'Beer',
    ingredients: 'Water, Barley Malt, Hops, Yeast',
    country: 'Germany',
    volume: '330',
  },
  {
    title: 'Big Drop Brewing Paradiso Citra Ipa',
    brand: 'Big Drop Brewing Co.',
    abv: '0.5',
    calories: '18.5',
    type: 'Beer',
    ingredients: 'Water, Barley, Oats, Wheat, Lactose (Milk) Hops, Yeast',
    country: 'UK',
    volume: '330',
  },
  {
    title: 'Birra Moretti Zero',
    brand: 'Birra Moretti',
    abv: '0',
    calories: '20',
    type: 'Beer',
    ingredients: 'Water, Barley Malt, Hop, Hop Extract, Natural Flavouring',
    country: 'Italy',
    volume: '330',
  },
  {
    title: 'Brewdog Punk Af',
    brand: 'Brewdog',
    abv: '0.5',
    calories: '15',
    type: 'Beer',
    ingredients:
      'Water, Lactose (Milk), Malted Barley, Hops, Yeast, Malted Oats, Malted Wheat, Lactic Acid',
    country: 'UK',
    volume: '330',
  },
  {
    title: 'Brooklyn Alcohol Free Hoppy Lager',
    brand: 'Brooklyn',
    abv: '0.4',
    calories: '29',
    type: 'Lager',
    ingredients: 'Water, Malted Barley, Hops',
    country: 'EU',
    volume: '330',
  },
  {
    title: 'Corona Cero Alcohol Free',
    brand: 'Corona',
    abv: '0',
    calories: '56',
    type: 'Lager',
    ingredients: 'Water, Barley Malt, Maize, Sugar, Hops, Natural Flavours',
    country: 'Belgium',
    volume: '330',
  },
  {
    title: 'Doom Bar Zero Amber Ale',
    brand: 'Doom Bar',
    abv: '0',
    calories: '13',
    type: 'Beer',
    ingredients:
      'Water, Malted Barley, Sugar, Oats, Hops and Hop Extracts, Antioxidant: Ascorbic Acid, Natural Flavours',
    country: 'UK',
    volume: '500',
  },
  {
    title: 'Erdinger Alkoholfrei Grapefruit',
    brand: 'Erdinger',
    abv: '0.3',
    calories: '25',
    type: 'Beer',
    ingredients:
      '50% Erdinger Alkoholfrei (Water, Wheat Malt, Barley Malt, Hops, Yeast, Carbon Dioxide), 50% Refreshment Drink with Grapefruit',
    country: 'Germany',
    volume: '330',
  },
  {
    title: 'Free Damm Lager',
    brand: 'Free Damm',
    abv: '0',
    calories: '20',
    type: 'Beer',
    ingredients:
      'Water, Barley Malt (8%), Maize, Glucose and Fructose Syrup, Rice, Hops',
    country: 'Spain',
    volume: '330',
  },
  {
    title: 'Heineken 0.0 Alcohol Free Lager',
    brand: 'Heineken',
    abv: '0.05',
    calories: '21',
    type: 'Lager',
    ingredients: 'Water, Malted Barley, Hop Extract, Natural Flavourings',
    country: 'Scotland',
    volume: '330',
  },
  {
    title: 'Kopparberg Alcohol Free Pear Cider',
    brand: 'Kopparberg',
    abv: '0.05',
    calories: '42',
    type: 'Cider',
    ingredients:
      'Carbonated Water, Fermented Pears, Pear Juice, Sugar, Acidifier (Citric Acid), Flavouring, Preservative (Potassium Sorbate), Antioxidant (E224/Sulphites)',
    country: 'Sweden',
    volume: '500',
  },
  {
    title: 'Kopparberg Cider Plus Strawberry & Lime Alcohol Free',
    brand: 'Kopparberg',
    abv: '0.05',
    calories: '41',
    type: 'Cider',
    ingredients:
      'Carbonated Water, Fermented Apples, Juice (Apple, Strawberry, Elderberry & Lime), Sugar, Flavouring, Acid (Citric Acid), Preservative (Potassium Sorbate), Antioxidant (E224/Sulphites)',
    country: 'Sweden',
    volume: '500',
  },
  {
    title: 'Kopparberg Mixed Fruit Alcohol Free',
    brand: 'Kopparberg',
    abv: '0.05',
    calories: '38',
    type: 'Cider',
    ingredients:
      'Carbonated Water, Fermented Apples, Juice (Apple, Blackcurrant, Elderberry, Raspberry), Sugar, Acidifier (Citric Acid), Flavouring, Preservative (Potassium Sorbate)',
    country: 'Sweden',
    volume: '500',
  },
  {
    title: 'Leffe Blonde 0% Alcohol Free Beer',
    brand: 'Leffe',
    abv: '0',
    calories: '40',
    type: 'Beer',
    ingredients:
      'Water, Barley Malt, Maize, Barley, Sugar, Hops, Natural Aromas',
    country: 'Belgium',
    volume: '250',
  },
  {
    title: 'Lucky Saint 0.5%',
    brand: 'Lucky Saint',
    abv: '0.5',
    calories: '16',
    type: 'Beer',
    ingredients: 'Water, Barley, Yeast, Hops',
    country: 'Germany',
    volume: '330',
  },
  {
    title: 'Peroni Nastro Azzurro 0.0%',
    brand: 'Peroni',
    abv: '0.05',
    calories: '23',
    type: 'Beer',
    ingredients: 'Water, Barley Malt, Italian Maize, Hops, Natural Flavours',
    country: 'Italy',
    volume: '330',
  },
  {
    title: 'San Miguel 0.0%',
    brand: 'San Miguel',
    abv: '0',
    calories: '24',
    type: 'Beer',
    ingredients: 'Water, Barley Malt, Hops, Flavourings',
    country: 'Spain',
    volume: '330',
  },
  {
    title: 'Shipyard Low Tide Pale Ale',
    brand: 'Shipyard',
    abv: '0.5',
    calories: '17',
    type: 'Beer',
    ingredients: 'Water, Barley, Wheat, Hops, Milk (Lactose), Yeast',
    country: 'UK',
    volume: '500',
  },
  {
    title: 'Stella Artois Premium Alcohol Free Lager',
    brand: 'Stella Artois',
    abv: '0',
    calories: '18',
    type: 'Beer',
    ingredients: 'Water, Malted Barley, Hops, Sugar, Natural Flavours',
    country: 'Belgium',
    volume: '330',
  },
  {
    title: 'Thatchers Zero Somerset Cider',
    brand: 'Thatchers',
    abv: '0.05',
    calories: '47',
    type: 'Cider',
    ingredients: 'Cider apples',
    country: 'UK',
    volume: '500',
  },
];

module.exports = data;